//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindWordNetUnitTestProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WordNetData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WordNetData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindWordNetUnitTestProject.WordNetData", typeof(WordNetData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### Taken from WNINPUT(5WN)
        ///!     Antonym 
        ///&amp;     Similar to 
        ///&lt;     Participle of verb 
        ///\     Pertainym (pertains to noun) 
        ///=     Attribute 
        ///^     Also see 
        ///;c     Domain of synset - TOPIC 
        ///;r     Domain of synset - REGION 
        ///;u     Domain of synset - USAGE 
        ///.
        /// </summary>
        internal static string AdjectivePointerSymbols {
            get {
                return ResourceManager.GetString("AdjectivePointerSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### Taken from WNINPUT(5WN)
        ///!     Antonym 
        ///\     Derived from adjective 
        ///;c     Domain of synset - TOPIC 
        ///;r     Domain of synset - REGION 
        ///;u     Domain of synset - USAGE .
        /// </summary>
        internal static string AdverbPointerSymbols {
            get {
                return ResourceManager.GetString("AdverbPointerSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Taken from LEXNAMES(5WN)
        ///File Number   Name   Contents   
        ///
        ///00  adj.all  all adjective clusters  
        ///01  adj.pert  relational adjectives (pertainyms)  
        ///02  adv.all  all adverbs  
        ///03  noun.Tops  unique beginner for nouns  
        ///04  noun.act  nouns denoting acts or actions  
        ///05  noun.animal  nouns denoting animals  
        ///06  noun.artifact  nouns denoting man-made objects  
        ///07  noun.attribute  nouns denoting attributes of people and objects  
        ///08  noun.body  nouns denoting body parts  
        ///09  noun.cognition  nouns [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LexicographerFiles {
            get {
                return ResourceManager.GetString("LexicographerFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### Taken from WNINPUT(5WN)
        ///!     Antonym 
        ///@     Hypernym 
        ///@i     Instance Hypernym 
        /// ~     Hyponym 
        /// ~i     Instance Hyponym 
        ///#m     Member holonym 
        ///#s     Substance holonym 
        ///#p     Part holonym 
        ///%m     Member meronym 
        ///%s     Substance meronym 
        ///%p     Part meronym 
        ///=     Attribute 
        ///+     Derivationally related form         
        ///;c     Domain of synset - TOPIC 
        ///-c     Member of this domain - TOPIC 
        ///;r     Domain of synset - REGION 
        ///-r     Member of this domain - REGION 
        ///;u     Domain of synse [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NounPointerSymbols {
            get {
                return ResourceManager.GetString("NounPointerSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Taken from WNDB(5WN)
        ///Syntactic category: n  for noun files, v  for verb files, a  for adjective files, r  for adverb files. .
        /// </summary>
        internal static string PartOfSpeech {
            get {
                return ResourceManager.GetString("PartOfSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Taken from SENSEIDX(5WN)
        ///1     NOUN 
        ///2     VERB 
        ///3     ADJECTIVE 
        ///4     ADVERB 
        ///5     ADJECTIVE SATELLITE .
        /// </summary>
        internal static string SynsetTypeNumber {
            get {
                return ResourceManager.GetString("SynsetTypeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Taken from WNDB(5WN)
        ///n     NOUN 
        ///v     VERB 
        ///a     ADJECTIVE 
        ///s     ADJECTIVE SATELLITE 
        ///r     ADVERB .
        /// </summary>
        internal static string SynsetTypeSymbol {
            get {
                return ResourceManager.GetString("SynsetTypeSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Taken from LEXNAMES(5WN)
        ///1     NOUN 
        ///2     VERB 
        ///3     ADJECTIVE 
        ///4     ADVERB .
        /// </summary>
        internal static string SyntacticCategories {
            get {
                return ResourceManager.GetString("SyntacticCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Taken from WNINPUT(5WN)
        ///(p)     predicate position 
        ///(a)     prenominal (attributive) position 
        ///(ip)     immediately postnominal position         .
        /// </summary>
        internal static string SyntacticMarkers {
            get {
                return ResourceManager.GetString("SyntacticMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Taken from WNINPUT(5WN)
        ///1    Something ----s
        ///2    Somebody ----s
        ///3    It is ----ing
        ///4    Something is ----ing PP
        ///5    Something ----s something Adjective/Noun
        ///6    Something ----s Adjective/Noun
        ///7    Somebody ----s Adjective
        ///8    Somebody ----s something
        ///9    Somebody ----s somebody
        ///10    Something ----s somebody
        ///11    Something ----s something
        ///12    Something ----s to somebody
        ///13    Somebody ----s on something
        ///14    Somebody ----s somebody something
        ///15    Somebody ----s something to somebo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VerbFrames {
            get {
                return ResourceManager.GetString("VerbFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### Taken from WNINPUT(5WN)
        ///!     Antonym 
        ///@     Hypernym 
        /// ~     Hyponym 
        ///*     Entailment 
        ///&gt;     Cause 
        ///^     Also see 
        ///$     Verb Group 
        ///+     Derivationally related form         
        ///;c     Domain of synset - TOPIC 
        ///;r     Domain of synset - REGION 
        ///;u     Domain of synset - USAGE 
        ///.
        /// </summary>
        internal static string VerbPointerSymbols {
            get {
                return ResourceManager.GetString("VerbPointerSymbols", resourceCulture);
            }
        }
    }
}
