//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordServer.WordNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Synset
    {
        public Synset()
        {
            this.SynsetPointers = new HashSet<SynsetPointer>();
            this.SynsetPointerTargets = new HashSet<SynsetPointer>();
            this.SynsetWords = new HashSet<SynsetWord>();
        }
    
        public System.Guid Id { get; set; }
        public short LexFileNum { get; set; }
        public long Offset { get; set; }
        public short SynsetType { get; set; }
        public string Definition { get; set; }
        public System.Guid SourceId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ICollection<SynsetPointer> SynsetPointers { get; set; }
        public virtual ICollection<SynsetPointer> SynsetPointerTargets { get; set; }
        public virtual ICollection<SynsetWord> SynsetWords { get; set; }
    }
}
