//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordServer.WordNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class SynsetWord
    {
        public System.Guid WordId { get; set; }
        public System.Guid SynsetId { get; set; }
        public short LexId { get; set; }
        public short Position { get; set; }
        public System.Guid SourceId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual IndexWord IndexWord { get; set; }
        public virtual Synset Synset { get; set; }
    }
}
